name: build conda packages

on:
  workflow_call:

jobs:
  build:
    name: Build conda
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install rattler-build
        uses: jaxxstorm/action-install-gh-release@v3.0.0
        with:
          repo: prefix-dev/rattler-build
          tag: v0.55.1
        env:
          GITHUB_TOKEN: "${{ github.token }}"

      - run: |
          rattler-build build \
            --wrap-log-lines=false \
            --log-style=plain \
            --skip-existing=all \
            --channel=conda-forge \
            --channel=https://repo.prefix.dev/trim21-pkg \
            --output-dir=./output \
            --verbose \
            --recipe-dir=packages
        shell: bash

      - run: ls ./output/

      - uses: actions/upload-artifact@v7
        with:
          name: "conda-linux-64"
          path: ./output/linux-64/*.conda
          if-no-files-found: ignore
